---
name: CI

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    name: Test
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2

      - name: Setup python
        uses: actions/setup-python@v4.1.0
        with:
          python-version: 3.9
